### ISSUE TITLE
Incompatibility with Rack 2.1.0 and higher

### ISSUE THREAD

**Issue by ignatbagaev** [ruby-grape/grape#1980]
Hi!
I use Grape in my application and after updating Rack to 2.1.1, I get an error
`NoMethodError - undefined method '[]' for nil:NilClass` without any backtrace. During debugging I found that it was raising in [Grape::Router#cascade?](https://github.com/ruby-grape/grape/blob/master/lib/grape/router.rb#L168)
```ruby
def cascade?(response)
  response && response[1][Grape::Http::Headers::X_CASCADE] == 'pass'
end
```
and the `response` looks like
```
[#<Rack::Response:0x00007fc561a338c8 @status=200, @header={"Content-Type"=>"application/json"}, @writer=#<Method: Rack::Response(Rack::Response::Helpers)#append>, @block=nil, @length=0, @body=["{\"foo\":\"bar\"}"], @buffered=false>, nil, nil]
```
I made some investigation and found that Rack team [removed](https://github.com/rack/rack/blob/master/CHANGELOG.md) `#to_ary` from Rack::Response in version 2.1.0 and this change made the result of `Grape::MIddleware::Formatter#build_formatted_response` not implicitly convertable to Array. This is why I had response like a mentioned above instead of response like
```
[response_status, response_headers, response_body]
```

To fix this behavior just `#finish` an instance of Rack::Response in Formatter middleware:
change
```ruby
Rack::Response.new(bodymap, status, headers)
```
at https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/formatter.rb#L49 to
```ruby
Rack::Response.new(bodymap, status, headers).finish
```

**Comment by dnesteryuk** [comment]
@ignatbagaev Did you try Grape 1.3.0? There was a fix made by @ioquatix

**Comment by ignatbagaev** [comment]
@dnesteryuk thanks for the quick response! I appreciate it!
No, I did not because `Grape 1.3.0` has a `dry-types >= 1.1.0` dependency which is currently incompatible with my app.
I can not see any changes by @ioquatix in changelog, so I do not really understand which fix you meant. Can you please provide a link to PR? And as I can see it in `master` branch the "broken" code is still there (instance of Rack::Response not `finished` in the Formatter middleware).

**Comment by ignatbagaev** [comment]
@dnesteryuk already found this PR and rechecked the master. Looks like 1.3.0 really fixes this issue.

I close the issue and related PR

Thank you!

**Comment by jimmybaker** [comment]
@ignatbagaev I have the same issue. I'm unable to upgrade to 1.3.0 because of the dry-types dependency. How did you solve this?
