### ISSUE TITLE
'context' undefined in rescue_from in 2.1.0

### ISSUE THREAD

**Issue by mscrivo** [ruby-grape/grape#2451]
After updating from 2.0 to 2.1, some of our error handling tests broke. We have various error handlers that would catch errors globally and log some info and we used the context for that. For example:

```rb
rescue_from :all do |e|
  log_context = {
    useragent: context.env['HTTP_USER_AGENT'],
    method: context.env['REQUEST_METHOD'],
    url: context.env['PATH_INFO'],
    querystring: context.env['QUERY_STRING'],
    ip: context.env['HTTP_X_REAL_IP'],
    accept: context.env['HTTP_ACCEPT'],
    content_type: context.env['CONTENT_TYPE'],
    params: context.params,
  }
  logger.log(e, log_context)
  error!(e, e.status)
end
```

But now with 2.1, we're getting:

```
NameError: undefined local variable or method `context' for #<#<Class:0x0000000323776e08>:0x0000000324f45700>
    ruby/lib/grape/error_handling.rb:103:in `block in <module:ErrorHandling>'
```

I'll try to dig in tomorrow to see if I can figure out which commit caused it, but figured I'd give folks a heads up

**Comment by krismichalski** [comment]
I believe it's because of https://github.com/ruby-grape/grape/pull/2363/ the `Grape::Middleware::Helpers` module is no longer eager loaded. Adding `helpers Grape::Middleware::Helpers` fixes the issue.

**Comment by ericproulx** [comment]
@krismichalski your close but the helper is included and loaded in [Grape::Middleware::Base](https://github.com/ruby-grape/grape/blob/3df163a114bbcbae5e4943380fa2ac699c068e47/lib/grape/middleware/base.rb#L6) and [Grape::Middleware::Auth::Base](https://github.com/ruby-grape/grape/blob/3df163a114bbcbae5e4943380fa2ac699c068e47/lib/grape/middleware/auth/base.rb#L7)

Nonetheless, I think I know what the issue, since #2377, `rescue_from` are `endpoint.instance_exec` instead of `instance_exec`. Since the endpoint, doesn't have the helper included, this is why doing `helpers Grape::Middleware::Helpers` make it works.

**Comment by krismichalski** [comment]
oh, I didn't notice it was loaded there, sorry for the wrong accusation ^^" I'm glad the root cause was discovered 👍

**Comment by dblock** [comment]
@krismichalski Can you please take a look at https://github.com/ruby-grape/grape/blob/master/UPGRADING.md and make sure it accurately describes this situation for the next person?

**Comment by ericproulx** [comment]
@mscrivo could you checkout my branch and see if it works ?

**Comment by mscrivo** [comment]
@ericproulx your branch seems to work great, our tests are passing

**Comment by dblock** [comment]
Thanks for fixing this @ericproulx.
