### ISSUE TITLE
Error: uninitialized constant Hashie when including Grape::Extensions::Hashie::Mash::ParamBuilder

### ISSUE THREAD

**Issue by cmavromoustakos** [ruby-grape/grape#1843]
I am trying to get the Hashie::Mash parameters to work and when I include the extension into my class it results in the error below.

```
module IndieNinja::API
  class Web::V1::Gigs < Grape::API
    include Grape::Extensions::Hashie::Mash::ParamBuilder
```

```
 4) IndieNinja::API::Web::V1 GET /gigs returns a 401 if the user is not authorized
     Failure/Error: get '/gigs'

     NameError:
       uninitialized constant Hashie
       Did you mean?  Hash
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/extensions/hashie/mash.rb:16:in `build_params'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/request.rb:13:in `params'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/endpoint.rb:246:in `block in run'
     # /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/endpoint.rb:243:in `run'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/endpoint.rb:313:in `block in build_stack'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/base.rb:31:in `call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/base.rb:24:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/base.rb:31:in `call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/base.rb:24:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/error.rb:38:in `block in call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/error.rb:37:in `catch'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/error.rb:37:in `call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/middleware/base.rb:24:in `call'
     # /usr/local/bundle/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/endpoint.rb:227:in `call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/endpoint.rb:221:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router/route.rb:72:in `exec'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:121:in `process_route'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:74:in `block in identity'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:93:in `transaction'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:72:in `identity'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:57:in `block in call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:137:in `with_optimization'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/router.rb:56:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:131:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:57:in `call!'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:52:in `call'
     # /usr/local/bundle/gems/grape-1.2.2/lib/grape/api.rb:51:in `call'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # ./spec/api/web/v1/gigs_spec.rb:12:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # ./spec/support/database_cleaner.rb:17:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/local/bundle/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
     # /usr/local/bundle/bin/rspec:23:in `load'
     # /usr/local/bundle/bin/rspec:23:in `<main>'
```

**Comment by cmavromoustakos** [comment]
Adding the below to the file fixes the issue.

```
require 'hashie'
```

**Comment by cmavromoustakos** [comment]
Also trying to set it globally results in:

```
[4] pry(main)> Grape.configure
NoMethodError: undefined method `configure' for Grape:Module
from (pry):4:in `<top (required)>'
[5] pry(main)> Grape.configure do |config|
[5] pry(main)*   config.param_builder = Grape::Extensions::Hashie::Mash::ParamBuilder
[5] pry(main)* end
NoMethodError: undefined method `configure' for Grape:Module
from (pry):5:in `<top (required)>'
[6] pry(main)>
```

**Comment by cmavromoustakos** [comment]
Apologies, I did not realize this is not on 1.2.2. Oooph that was a waste of both of our times.

**Comment by dblock** [comment]
And assuming this works in 1.2.2 (HEAD) as expected?

**Comment by cmavromoustakos** [comment]
> And assuming this works in 1.2.2 (HEAD) as expected?

Yes, sorry just saw this. It does in fact work on head as expected.
